# Generated by Django 4.1.3 on 2022-11-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(help_text='Entre a Descrição', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(help_text='Entre o Título', max_length=100, unique=True, verbose_name='Título'),
        ),
    ]
